services:
  lms:
    container_name: lms
    image: ${IMAGE_NAME}:${LMS_TAG}
    expose:
      - "5082"
    ports:
      - "${LMS_PORT:-80}:5082"
    volumes:
      - ${MUSIC_PATH:-/music}:/music
      - ${DOCKER_DATA_PATH:-/docker}/lms/usr/local/etc:/usr/local/etc
      - ${DOCKER_DATA_PATH:-/docker}/lms/var/lms:/var/lms
    environment:
      - LMS_API_KEY=${LMS_API_KEY}
      - LMS_SUBSONIC_API_KEY=${LMS_SUBSONIC_API_KEY}
      - LMS_MUSIC_MANAGEMENT_URL=${MUSIC_MANAGEMENT_URL}
      - LMS_MUSIC_MANAGEMENT_API_KEY=${MUSIC_MANAGEMENT_API_KEY}
    networks:
      - default
      - music-management_db
    user: "0:0"
    restart: unless-stopped
  lms_alpha:
    container_name: lms_alpha
    image: ${IMAGE_NAME}:${LMS_ALPHA_TAG}
    expose:
      - "5082"
    ports:
      - "${LMS_ALPHA_PORT:-8080}:5082"
    volumes:
      - ${MUSIC_PATH:-/music}:/music
      - ${DOCKER_DATA_PATH:-/docker}/alpha-lms/usr/local/etc:/usr/local/etc
      - ${DOCKER_DATA_PATH:-/docker}/alpha-lms/var/lms:/var/lms
    environment:
      - LMS_API_KEY=${LMS_API_KEY}
      - LMS_SUBSONIC_API_KEY=${LMS_SUBSONIC_API_KEY}
      - LMS_MUSIC_MANAGEMENT_URL=${MUSIC_MANAGEMENT_URL}
      - LMS_MUSIC_MANAGEMENT_API_KEY=${MUSIC_MANAGEMENT_API_KEY}
    networks:
      - default
      - music-management_db
    user: "0:0"
    restart: unless-stopped

networks:
  music-management_db:
    external: true
    name: music-management_db
