services:
  lms:
    container_name: lms
    image: ${IMAGE_NAME:-tsshadow/lms}:${LMS_TAG:-stable}
    expose:
      - "5082"
    ports:
      - "${LMS_PORT:-80}:5082"
    volumes:
      - ${MUSIC_PATH:-/mnt/music}:/music
      - ${DOCKER_DATA_PATH:-/docker}/lms/usr/local/etc:/usr/local/etc
      - ${DOCKER_DATA_PATH:-/docker}/lms/var/lms:/var/lms
    user: "0:0"
    restart: unless-stopped
  lms_alpha:
    container_name: lms_alpha
    image: ${IMAGE_NAME:-tsshadow/lms}:${LMS_ALPHA_TAG:-latest}
    expose:
      - "5082"
    ports:
      - "${LMS_ALPHA_PORT:-8080}:5082"
    volumes:
      - ${MUSIC_PATH:-/mnt/music}:/music
      - ${DOCKER_DATA_PATH:-/docker}/alpha-lms/usr/local/etc:/usr/local/etc
      - ${DOCKER_DATA_PATH:-/docker}/alpha-lms/var/lms:/var/lms
    user: "0:0"
    restart: unless-stopped