name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: A clear and concise description of what the feature should do.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
  - type: textarea
    id: alternatives
    attributes:
      label: Proposed Solution / Alternatives
      description: Describe the solution you'd like or any alternative solutions you've considered.
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
